const $=s=>document.querySelector(s);let supabase,token;
async function init(){try{const cfg=await fetch('/api/config',{cache:'no-store'}).then(r=>r.json());const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2');supabase=createClient(cfg.supabase.url,cfg.supabase.publishableKey);const {data}=await supabase.auth.getSession();if(!data.session)return location.replace('/');token=data.session.access_token;const role=data.session.user?.app_metadata?.role;if(role!=='admin'){toast('Accès administrateur refusé');return setTimeout(()=>location.replace('/'),900)}$('#adminEmail').textContent=data.session.user.email||'Administrateur';bind();await loadOverview();}catch(e){console.error(e);toast('Impossible de vérifier la session : '+e.message);setTimeout(()=>location.replace('/'),1200)}}
async function api(path,options={}){try{const r=await fetch('/api/admin'+path,{...options,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers||{})}});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{}if(!r.ok){const err=new Error(d.error||d.message||`Erreur HTTP ${r.status}`);err.status=r.status;err.code=d.code;throw err}return d}catch(e){if(e instanceof TypeError)throw new Error('Serveur IZISONO inaccessible. Vérifie que npm.cmd start est lancé sur le port 3000.');throw e}}
async function loadOverview(){try{const d=await api('/overview');$('#usersCount').textContent=d.users;$('#tracksCount').textContent=d.tracks;$('#paymentsCount').textContent=d.successfulPayments;$('#creditsCount').textContent=d.totalCredits;$('#failedJobs').textContent=d.failedJobs;$('#successfulJobs').textContent=d.successfulJobs}catch(e){toast('Erreur vue d’ensemble : '+e.message);console.error(e)}}
async function refreshButton(id,fn){const b=document.getElementById(id);if(!b)return;const old=b.textContent;b.disabled=true;b.textContent='Actualisation…';try{await fn();}finally{b.disabled=false;b.textContent=old}}
async function loadUsers(){try{const d=await api('/users');$('#usersTable').innerHTML=d.users.map(u=>`<tr><td>${esc(u.email)}</td><td><b>${u.credits}</b></td><td>${u.suspended?'<span class="danger">Suspendu</span>':u.confirmed?'<span class="ok">Actif ✓</span>':'<span>Non confirmé</span>'}</td><td>${fmt(u.last_sign_in_at)}</td><td class="actions"><button data-action="credits" data-id="${u.id}" data-amount="1">+1</button><button data-action="credits" data-id="${u.id}" data-amount="-1">−1</button><button data-action="credits" data-id="${u.id}" data-amount="10">+10</button><button data-action="suspend" data-id="${u.id}" data-suspended="${!u.suspended}">${u.suspended?'Réactiver':'Suspendre'}</button><button class="danger-btn" data-action="delete" data-id="${u.id}" data-email="${escAttr(u.email)}">Supprimer</button></td></tr>`).join('')||emptyRow(5);toast(`Utilisateurs actualisés — ${d.users.length} compte(s)`)}catch(e){toast('Actualisation impossible : '+e.message);console.error(e)}}
async function loadTracks(){try{const d=await api('/tracks');$('#tracksTable').innerHTML=d.tracks.map(t=>`<tr><td>${esc(t.title||'Sans titre')}</td><td>${esc(t.genre||'—')}</td><td>${badge(t.status)}</td><td>${t.public?'Oui':'Non'}</td><td>${fmt(t.created_at)}</td><td class="actions"><button data-action="public" data-id="${t.id}" data-public="${!t.public}">${t.public?'Privatiser':'Publier'}</button><button class="danger-btn" data-action="delete-track" data-id="${t.id}" data-title="${escAttr(t.title||'cette chanson')}">Supprimer</button></td></tr>`).join('')||emptyRow(6);toast(`Chansons actualisées — ${d.tracks.length}`)}catch(e){toast('Actualisation impossible : '+e.message);console.error(e)}}
async function loadGenerations(){try{const d=await api('/generations');$('#generationsTable').innerHTML=d.generations.map(g=>`<tr><td>${esc(g.provider||'—')}</td><td><code>${esc(g.provider_task_id||'—')}</code></td><td>${badge(g.status)}</td><td>${esc(g.track_id||'—')}</td><td>${fmt(g.created_at)}</td></tr>`).join('')||emptyRow(5);toast(`Générations actualisées — ${d.generations.length}`)}catch(e){toast('Actualisation impossible : '+e.message);console.error(e)}}
async function loadPayments(){try{const d=await api('/payments');$('#paymentsTable').innerHTML=d.payments.map(p=>`<tr><td>${esc(p.plan_id||'—')}</td><td>${Number(p.amount||0).toLocaleString('fr-FR')} ${p.currency||'XOF'}</td><td>${p.credits}</td><td>${badge(p.status)}</td><td>${esc(p.method||'—')}</td><td>${fmt(p.created_at)}</td><td class="actions"><select data-action="payment" data-id="${p.id}"><option value="">Changer…</option><option value="pending">pending</option><option value="initiated">initiated</option><option value="failed">failed</option><option value="cancelled">cancelled</option></select><button data-action="reconcile" data-id="${p.id}">Vérifier PayDunya</button></td></tr>`).join('')||emptyRow(7);toast(`Paiements actualisés — ${d.payments.length}`)}catch(e){toast('Actualisation impossible : '+e.message);console.error(e)}}
async function adjustCredits(id,amount){try{await api(`/users/${id}/credits`,{method:'PATCH',body:JSON.stringify({amount})});toast(`Crédits ${amount>0?'+':''}${amount}`);await loadUsers();await loadOverview()}catch(e){toast('Erreur crédits : '+e.message)}}
async function toggleSuspend(id,suspended){if(!confirm(suspended?'Suspendre cet utilisateur ?':'Réactiver cet utilisateur ?'))return;try{await api(`/users/${id}/suspend`,{method:'PATCH',body:JSON.stringify({suspended})});toast(suspended?'Utilisateur suspendu':'Utilisateur réactivé');await loadUsers()}catch(e){toast('Erreur suspension : '+e.message);console.error(e)}}
async function deleteUser(id,email){if(!confirm(`Supprimer définitivement ${email} ? Cette action est irréversible.`))return;try{await api(`/users/${id}`,{method:'DELETE'});toast('Utilisateur supprimé');await loadUsers();await loadOverview()}catch(e){toast('Erreur suppression : '+e.message);console.error(e)}}
async function togglePublic(id,publicValue){try{await api(`/tracks/${id}`,{method:'PATCH',body:JSON.stringify({public:publicValue})});toast(publicValue?'Chanson publiée':'Chanson rendue privée');await loadTracks()}catch(e){toast('Erreur publication : '+e.message)}}
async function deleteTrack(id,title){if(!confirm(`Supprimer ${title} ? Cette action est irréversible.`))return;try{await api(`/tracks/${id}`,{method:'DELETE'});toast('Chanson supprimée');await loadTracks();await loadOverview()}catch(e){toast('Erreur suppression : '+e.message)}}
async function updatePayment(id,status){if(!status)return;if(!confirm(`Changer le statut du paiement en « ${status} » ?`))return;try{await api(`/payments/${id}`,{method:'PATCH',body:JSON.stringify({status})});toast('Paiement mis à jour');await loadPayments();await loadOverview()}catch(e){toast('Erreur paiement : '+e.message)}}
async function reconcilePayment(id){if(!confirm('Vérifier ce paiement directement auprès de PayDunya et appliquer le crédit si le paiement est réellement réussi ?'))return;try{const r=await api(`/payments/${id}/reconcile`,{method:'POST'});toast(r.credited?`Paiement confirmé : +${r.creditsAdded} Notes`:'Paiement déjà traité ou non confirmé');await loadPayments();await loadOverview();}catch(e){toast('Réconciliation impossible : '+e.message)}}
function bind(){document.querySelectorAll('.nav').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');const s=b.dataset.section;document.querySelectorAll('.section').forEach(x=>x.hidden=x.id!==s);$('#title').textContent=b.textContent.replace(/^\S+\s/,'');if(s==='users')await loadUsers();if(s==='tracks')await loadTracks();if(s==='generations')await loadGenerations();if(s==='payments')await loadPayments();if(s==='overview')await loadOverview()});
$('#refreshUsers').onclick=()=>refreshButton('refreshUsers',loadUsers);$('#refreshTracks').onclick=()=>refreshButton('refreshTracks',loadTracks);$('#refreshGenerations').onclick=()=>refreshButton('refreshGenerations',loadGenerations);$('#refreshPayments').onclick=()=>refreshButton('refreshPayments',loadPayments);
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='credits')adjustCredits(b.dataset.id,Number(b.dataset.amount));if(a==='suspend')toggleSuspend(b.dataset.id,b.dataset.suspended==='true');if(a==='delete')deleteUser(b.dataset.id,b.dataset.email);if(a==='public')togglePublic(b.dataset.id,b.dataset.public==='true');if(a==='delete-track')deleteTrack(b.dataset.id,b.dataset.title);if(a==='reconcile')reconcilePayment(b.dataset.id)});document.addEventListener('change',e=>{const s=e.target.closest('[data-action="payment"]');if(s)updatePayment(s.dataset.id,s.value)});$('#logout').onclick=async()=>{await supabase.auth.signOut();location.replace('/')};}
function emptyRow(n){return `<tr><td colspan="${n}">Aucune donnée.</td></tr>`}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function escAttr(v){return esc(v).replace(/`/g,'&#96;')}function fmt(v){return v?new Date(v).toLocaleString('fr-FR'):'—'}function badge(v){return `<span>${esc(v||'—')}</span>`}function toast(m){const t=$('#toast');t.textContent=m;t.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.style.display='none',4000)}
window.loadUsers=loadUsers;window.loadTracks=loadTracks;window.loadGenerations=loadGenerations;window.loadPayments=loadPayments;window.adjustCredits=adjustCredits;window.toggleSuspend=toggleSuspend;window.deleteUser=deleteUser;window.togglePublic=togglePublic;window.deleteTrack=deleteTrack;window.updatePayment=updatePayment;window.reconcilePayment=reconcilePayment;
init();
