-- Already applied to the connected izisono Supabase project.
-- Kept in the ZIP for reproducible deployment.
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,email text,credits integer not null default 4 check (credits >= 0),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.tracks (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,prompt text not null default '',lyrics text not null default '',genre text,mood text,language text not null default 'fr',duration integer,voice text,instrumental boolean not null default false,occasion text,provider text not null default 'mureka',provider_task_id text,provider_song_id text,status text not null default 'queued',failed_reason text,audio_url text,public boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists tracks_user_id_created_at_idx on public.tracks(user_id,created_at desc);
create index if not exists tracks_provider_task_id_idx on public.tracks(provider_task_id);
create index if not exists tracks_public_created_at_idx on public.tracks(public,created_at desc);
create table if not exists public.generation_jobs (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,track_id uuid references public.tracks(id) on delete cascade,provider text not null default 'mureka',provider_task_id text,status text not null default 'queued',request jsonb not null default '{}'::jsonb,response jsonb,error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists generation_jobs_user_created_idx on public.generation_jobs(user_id,created_at desc);
create index if not exists generation_jobs_provider_task_idx on public.generation_jobs(provider_task_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security invoker as $$ begin insert into public.profiles(id,email) values(new.id,new.email) on conflict(id) do update set email=excluded.email; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
alter table public.profiles enable row level security; alter table public.tracks enable row level security; alter table public.generation_jobs enable row level security;
drop policy if exists profiles_select_own on public.profiles; create policy profiles_select_own on public.profiles for select to authenticated using ((select auth.uid())=id);
drop policy if exists profiles_update_own on public.profiles; create policy profiles_update_own on public.profiles for update to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id);
drop policy if exists tracks_select_own_or_public on public.tracks; create policy tracks_select_own_or_public on public.tracks for select to authenticated using ((select auth.uid())=user_id or public=true);
drop policy if exists tracks_insert_own on public.tracks; create policy tracks_insert_own on public.tracks for insert to authenticated with check ((select auth.uid())=user_id);
drop policy if exists tracks_update_own on public.tracks; create policy tracks_update_own on public.tracks for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
drop policy if exists tracks_delete_own on public.tracks; create policy tracks_delete_own on public.tracks for delete to authenticated using ((select auth.uid())=user_id);
drop policy if exists jobs_select_own on public.generation_jobs; create policy jobs_select_own on public.generation_jobs for select to authenticated using ((select auth.uid())=user_id);
drop policy if exists jobs_insert_own on public.generation_jobs; create policy jobs_insert_own on public.generation_jobs for insert to authenticated with check ((select auth.uid())=user_id);
drop policy if exists jobs_update_own on public.generation_jobs; create policy jobs_update_own on public.generation_jobs for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
grant select,insert,update,delete on public.tracks to authenticated;
grant select,insert,update on public.profiles to authenticated;
grant select,insert,update on public.generation_jobs to authenticated;


-- Moneroo v9 payment ledger and idempotent crediting.
create table if not exists public.payment_transactions (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,moneroo_payment_id text not null,plan_id text not null,amount integer not null check (amount > 0),currency text not null default 'XOF',credits integer not null check (credits > 0),status text not null default 'initiated',method text,gateway text,raw_payload jsonb not null default '{}'::jsonb,processed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists payment_transactions_moneroo_payment_id_uidx on public.payment_transactions(moneroo_payment_id);
create index if not exists payment_transactions_user_created_idx on public.payment_transactions(user_id,created_at desc);
alter table public.payment_transactions enable row level security;
revoke all on table public.payment_transactions from anon, authenticated;
grant select on public.payment_transactions to authenticated;
drop policy if exists payment_transactions_select_own on public.payment_transactions;
create policy payment_transactions_select_own on public.payment_transactions for select to authenticated using ((select auth.uid())=user_id);
create or replace function public.record_payment_transaction(p_user_id uuid,p_moneroo_payment_id text,p_plan_id text,p_amount integer,p_currency text,p_credits integer,p_status text,p_method text default null,p_gateway text default 'moneroo',p_raw_payload jsonb default '{}'::jsonb) returns public.payment_transactions language plpgsql security definer set search_path = public as $$ declare v_row public.payment_transactions; begin insert into public.payment_transactions(user_id,moneroo_payment_id,plan_id,amount,currency,credits,status,method,gateway,raw_payload) values(p_user_id,p_moneroo_payment_id,p_plan_id,p_amount,p_currency,p_credits,p_status,p_method,p_gateway,coalesce(p_raw_payload,'{}'::jsonb)) on conflict(moneroo_payment_id) do update set status=case when payment_transactions.status='success' then 'success' else excluded.status end,method=coalesce(excluded.method,payment_transactions.method),gateway=coalesce(excluded.gateway,payment_transactions.gateway),raw_payload=excluded.raw_payload,updated_at=now() returning * into v_row; return v_row; end; $$;
create or replace function public.apply_moneroo_payment(p_user_id uuid,p_moneroo_payment_id text,p_plan_id text,p_amount integer,p_currency text,p_credits integer,p_status text,p_method text default null,p_gateway text default 'moneroo',p_raw_payload jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path = public as $$ declare v_tx public.payment_transactions; v_new_credits integer; begin if upper(p_currency)<>'XOF' then raise exception 'payment_currency_invalid'; end if; insert into public.payment_transactions(user_id,moneroo_payment_id,plan_id,amount,currency,credits,status,method,gateway,raw_payload,processed_at,updated_at) values(p_user_id,p_moneroo_payment_id,p_plan_id,p_amount,p_currency,p_credits,'success',p_method,p_gateway,coalesce(p_raw_payload,'{}'::jsonb),now(),now()) on conflict(moneroo_payment_id) do nothing returning * into v_tx; if v_tx.id is null then select credits into v_new_credits from public.profiles where id=p_user_id; return jsonb_build_object('credited',false,'creditsAdded',0,'totalCredits',v_new_credits,'status','success','paymentId',p_moneroo_payment_id,'alreadyProcessed',true); end if; update public.profiles set credits=credits+p_credits,updated_at=now() where id=p_user_id returning credits into v_new_credits; if not found then delete from public.payment_transactions where id=v_tx.id; raise exception 'profile_not_found_for_payment'; end if; return jsonb_build_object('credited',true,'creditsAdded',p_credits,'totalCredits',v_new_credits,'status','success','paymentId',p_moneroo_payment_id,'alreadyProcessed',false); end; $$;
revoke all on function public.record_payment_transaction(uuid,text,text,integer,text,integer,text,text,text,jsonb) from public,anon,authenticated; grant execute on function public.record_payment_transaction(uuid,text,text,integer,text,integer,text,text,text,jsonb) to service_role;
revoke all on function public.apply_moneroo_payment(uuid,text,text,integer,text,integer,text,text,text,jsonb) from public,anon,authenticated; grant execute on function public.apply_moneroo_payment(uuid,text,text,integer,text,integer,text,text,text,jsonb) to service_role;
-- Remove legacy overloaded RPC to keep the Moneroo payment function unambiguous.
drop function if exists public.apply_moneroo_payment(uuid,text,text,integer,text,integer,text,text,jsonb);
